name: "🐞 Bug Report"
description: "Report a bug to help us improve the project"
title: "[BUG] :"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ### 🐞 Thanks for taking the time to report a bug!  
        Please provide the following details to help us resolve the issue.  
        _(Fields marked with a `*` are required)_

  - type: input
    id: bug_title
    attributes:
      label: "⚠️ Bug Summary"
      description: "Briefly describe the bug. *"
      placeholder: "e.g. App crashes on launch"
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "🧩 Steps to Reproduce"
      description: "Steps to reproduce the behavior. *"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected behavior"
      description: "Describe what you expected to happen. *"
      placeholder: "e.g. The app should load the dashboard screen."

  - type: textarea
    id: actual_behavior
    attributes:
      label: "❌ Actual behavior"
      description: "Describe what actually happens when the bug occurs. *"
      placeholder: "e.g. The app crashes and closes immediately."

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "If applicable, add screenshots to help explain the problem."
      placeholder: "Optional"

  - type: input
    id: environment_info
    attributes:
      label: "💻 Environment Details"
      description: "Please provide details about your environment (OS, Browser, Version, etc.). *"
      placeholder: "e.g. Windows 10, Chrome 92"
    validations:
      required: true
